import { motion } from "framer-motion";

export default function Hero() {
  return (
    <div className="relative mx-auto max-w-6xl px-6 pt-14">
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, ease: "easeOut" }}
        className="flex flex-col gap-4"
      >
        <div className="inline-flex w-fit items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1 text-xs text-white/80 shadow-neon">
          <span className="h-2 w-2 rounded-full bg-emerald-400/80 shadow-[0_0_25px_rgba(16,185,129,.35)]" />
          CPIC-aligned PGx reports • VCF + drug input
        </div>

        <h1 className="text-balance text-4xl font-semibold tracking-tight text-white md:text-5xl">
          PharmaGuard AI –{" "}
          <span className="bg-gradient-to-r from-indigo-300 via-emerald-200 to-cyan-200 bg-clip-text text-transparent">
            Precision Medicine Engine
          </span>
        </h1>

        <p className="max-w-3xl text-pretty text-sm leading-relaxed text-white/70 md:text-base">
          Upload a VCF, select drugs, and receive a pharmacogenomic risk report driven by your configured CPIC rules and diplotype mappings.
          Explanations are generated by an LLM, but the clinical risk is never decided by AI.
        </p>
      </motion.div>
    </div>
  );
}

